
# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Openflow Quanta Agent Debian Archive
  get_url:
    url: https://github.com/onfsdn/atrium-docs/blob/master/16A/ONOS/builds/ofdpa-ly8_0.3.0.5.0-EA5-qct-01.01_amd64.deb?raw=true
    validate_certs: false
    checksum: "sha256:f8201530b1452145c1a0956ea1d3c0402c3568d090553d0d7b3c91a79137da9e"
    dest: /mnt/onl/data/ofdpa-ly8_0.3.0.5.0-EA5-qct-01.01_amd64.deb

- name: Openflow Agent Installed
  apt: deb="/mnt/onl/data/ofdpa-ly8_0.3.0.5.0-EA5-qct-01.01_amd64.deb" force=true
  when: not lsb_stat.stat.exists or dist.stdout == "0"
