---

- name: "Install apt dependencies"
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-dev
    - libffi-dev
    - python-pip
    - libssl-dev
    - sshpass

- name: Ansible APT Repository
  become: yes
  apt_repository:
    repo: "{{ ansible_apt_repo | default('ppa:ansible/ansible') }}"
  register: result
  until: result | success
  retries: 3
  delay: 10

- name: Install Ansible using APT
  become: yes
  apt:
    name: ansible=2.3*
    state: present
